#!/bin/sh

prompt() {
	read -r YESNO
	if [ "$YESNO" = "yes" ]; then
		return
	elif [ "$YESNO" = "no" ]; then
		echo "[ ERROR ] Cancelled" && exit 1
	else
		prompt
	fi
}

choose_drive(){
	fdisk -l | grep "[A-Za-z]* /dev/[a-z]*" | sed 's/:.*//g ; s/^.* //g'
	echo -e "\nChoose the disk: (/dev/sdX)"
	read -r DRIVE
	[ -z $DRIVE ] && echo "[ ERROR ] \$DRIVE can't be NULL" && exit 1
	if [ $(fdisk -l | grep "$DRIVE" | wc -l) -gt 0 ]; then
		echo "[ OK ] Found $DRIVE"
	else 
		echo "[ ERROR ] $DRIVE not found" && exit 1
	fi
	echo -e "\nAre you sure $DRIVE is the correct location? (yes/no)"
	prompt
}

user_zone(){
	echo -e "\nRegion: (Default: Asia)"
	read -r REGION
	[ -z $REGION ] && REGION="Asia"
	echo -e "\nNearest Big City: (Default: Jakarta)"
	read -r CITY
	[ -z $CITY ] && CITY="Jakarta"
	cat /usr/share/zoneinfo/$REGION/$CITY >/dev/null || user_zone
}

local_setting(){
	#clock
	user_zone
	ln -sf /usr/share/zoneinfo/$REGION/$CITY /etc/localtime
	hwclock --systohc
	
	#locale
	sed -i 's/\#en_US\./en_US\./g' /etc/locale.gen
	locale-gen
	pacman -S --noconfirm grub os-prober
	choose_drive
	grub-install --recheck $DRIVE
	grub-mkconfig -o /boot/grub/grub.cfg
}

ask_pass(){	
	echo -e "Password:"
	read -s PASS
	echo -e "\nRetype Password:"
	read -s RE_PASS
	echo ""

	[ ! "$PASS" = "$RE_PASS" ] && ask_pass
}

set_user(){
	echo -e "\nUsername:"
	read -r USER
	ask_pass
	(
	echo $PASS
	echo $PASS
	) | passwd
	
	useradd -m $USER
	(
	echo $PASS
	echo $PASS
	) | passwd $USER
	usermod -aG games,video,storage,optical,audio,wheel $USER
	sed -i 's/\# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers

	echo $USER > /etc/hostname
	pacman -S --noconfirm dhcpcd connman-openrc connman-gtk cmst || pacman -S --noconfirm dhcpcd connman-openrc connman-gtk
	rc-update add connmand
	
	# network
	ip -s link
	echo -e "\nPut in the correct interface:"
	read -r INT
	echo "
	config_$INT=\"dhcp\"" >> /etc/conf.d/net
	ln -s /etc/init.d/net.lo /etc/init.d/net.$INT
	rc-update add net.$INT default
	
	# dhcpcd
	echo "Checking dhcpcd..."
	[ "$(pacman -Q | grep "dhcpcd")" ] || pacman -S --noconfirm dhcpcd connman-openrc connman-gtk

	# download rc-network
	echo "Downloading rc-network..."
	curl -LOs https://raw.githubusercontent.com/null2264/autorice-zi/master/bin/rc-network && chmod +x rc-network && mv rc-network /usr/local/bin/
	
	echo -e "Install completed\n"
	echo -e "Now type:\nexit\numount -R /mnt\nreboot"
	exit
}

# Process
local_setting
set_user
