#!/bin/sh
# ===================================================================
# | install-zi | Auto install artix-linux			    |
# -------------------------------------------------------------------
# | Author: Ahmad Ansori Palembani <banipalemban@gmail.com>	    |
# | License: NULL						    |
# ===================================================================

prompt() {
	read -r YESNO
	if [ "$YESNO" = "yes" ]; then
		return
	elif [ "$YESNO" = "no" ]; then
		echo "[ ERROR ] Cancelled" && exit 1
	else
		prompt
	fi
}

prompt_curse(){
	dialog --yesno "$1" 0 0 2>&1 > /dev/tty || exit 1
	return
}

sel_drive(){
	DRIVE_LIST=( $(lsblk -nrpo "name,size" | grep "\/dev\/[a-z]* " ) )
	DRIVE=$(dialog --menu "Choose the correct drive" 0 0 0 ${DRIVE_LIST[@]} 2>&1 > /dev/tty)
	[ -z $DRIVE ] && echo "[ ERROR ] Cancelled" && exit 1
	prompt_curse "Are you sure $DRIVE is the correct location?"
}

checksudo() {
	if [ "$(id -u)" != "0" ]; then
		echo "[ ERROR ] Script must be run as sudo!" && exit 1
	fi
}

prepare(){
	pacman --noconfirm -Sy dialog
	dialog --title "autorice-zi - [install-zi]" --msgbox "\nWelcome to install-zi.\nThis script is part of autorice-zi, it's created to install Artix Linux OS automatically.\n" 0 0
}

welcome(){
	dialog --title "[install-zi] - Welcome" --yesno "\nWould you like to install Artix Linux?" 0 0 || exit
}

diskpart() {
	# fdisk -l | grep "[A-Za-z]* /dev/[a-z]*" | sed 's/:.*//g ; s/^.* //g'
	# echo -e "\nChoose the disk: (/dev/sdX)"
	# read -r DRIVE
	# [ -z $DRIVE ] && echo "[ ERROR ] \$DRIVE can't be NULL" && exit 1
	# if [ $(fdisk -l | grep "$DRIVE" | wc -l) -gt 0 ]; then
	# 	echo "[ OK ] Found $DRIVE"
	# else 
	# 	echo "[ ERROR ] $DRIVE not found" && exit 1
	# fi
	# echo -e "\nAre you sure $DRIVE is the correct location? (yes/no)"
	# prompt

	sel_drive
	echo ""
	RAM_TOTAL=$(free --giga | grep "Mem" | sed 's/^[A-Za-z]*: *//g;s/ .*//g')
	[ ! $RAM_TOTAL -gt 0 ] && RAM_TOTAL=1
	[ ! $RAM_TOTAL -gt 4 ] && ((SWAP=$RAM_TOTAL*2)) || SWAP=8
	(
	echo o # Create new DOS/MBR disklabel
	echo n # New partition
	echo p # Make it primary
	echo 1 # Partition number 1
	echo   # First sector default
	echo +$SWAP\G # Size: 4G
	echo t # change partition type
	echo 82 # to swap
	echo n # New partition
	echo p # Primary
	echo 2 # Number 2
	echo   # First sector default
	echo   # Size: the rest of the disk
	echo t # change partition type
	echo 2 # choose partition number 2
	echo 83 # to Linux (to make sure it is Linux)
	echo a # toggle bootable
	echo 2 # choose partition number 2
	echo w # write
	) | fdisk $DRIVE
	echo "Done"
}

diskpart_setting(){
	mkfs.ext4 -L ROOT $DRIVE\2
	mkswap -L SWAP $DRIVE\1

	swapon /dev/disk/by-label/SWAP
	mount /dev/disk/by-label/ROOT /mnt
	mkdir /mnt/boot
	mkdir /mnt/home
}

check_internet(){
	[ "$(ping -q -c 1 -W 1 artixlinux.org)" ] && echo " [ OK ] Connected to Internet" || exit 1
}

init_install(){
	check_internet && pacman -Syy
	basestrap /mnt base base-devel openrc linux linux-firmware
	echo "Installation will start in 5 second...." && sleep 5s && echo "Installing..."
	fstabgen -U /mnt >>/mnt/etc/fstab
	echo -e "\nArtix Linux has been install, you may now run chroot-os (./chroot-zi or sh chroot-zi)"
	curl -LOs https://raw.githubusercontent.com/null2264/autorice-zi/master/chroot-zi && chmod +x chroot-os && mv chroot-os /mnt/
	artools-chroot /mnt
}

# Installation steps
checksudo
prepare
welcome
clear
diskpart
diskpart_setting
init_install
