#!/bin/sh

checksudo() {
	if [ "$(id -u)" != "0" ]; then
		echo "[ ERROR ] Script must be run as sudo!" && exit 1
	fi
}

checkdisks() {
	fdisk -l
	echo -e "\nChoose the disk: (/dev/sdX)"
	read -r DRIVE
	echo -e ""
	(
	echo o # Create new DOS disklabel
	echo n
	echo p
	echo 1
	echo 
	echo +4G
	echo w
	) | fdisk $DRIVE
	echo "Done"
}

# Installation steps
checksudo
checkdisks
