#!/bin/sh

prompt() {
	read -r YESNO
	if [ "$YESNO" = "yes" ]; then
		return
	elif [ "$YESNO" = "no" ]; then
		echo "[ ERROR ] Cancelled" && exit 1
	else
		prompt
	fi
}

checksudo() {
	if [ "$(id -u)" != "0" ]; then
		echo "[ ERROR ] Script must be run as sudo!" && exit 1
	fi
}

diskpart() {
	fdisk -l
	echo -e "\nChoose the disk: (/dev/sdX)"
	read -r DRIVE
	[ -z $DRIVE ] && echo "[ ERROR ] \$DRIVE can't be NULL" && exit 1
	if [ $(fdisk -l | grep "$DRIVE" | wc -l) -gt 0 ]; then
		echo "[ OK ] Found $DRIVE"
	else 
		echo "[ ERROR ] $DRIVE not found" && exit 1
	fi
	echo -e "\nAre you sure $DRIVE is the correct location? (yes/no)"
	prompt
	echo ""
	free --giga
	echo -e "\nEnter your RAM value: (Eg: 5)"
	read -r RAM_TOTAL
	[ -z $RAM_TOTAL ] && echo "[ ERROR ] \$RAM_TOTAL can't be NULL" && exit 1
	[ ! $RAM_TOTAL -gt 0 ] && echo "[ ERROR ] \$RAM_TOTAL can't be smaller than 1" && exit 1
	[ ! $RAM_TOTAL -gt 4 ] && ((SWAP=$RAM_TOTAL*2)) || SWAP=8
	(
	echo o # Create new DOS/MBR disklabel
	echo n # New partition
	echo p # Make it primary
	echo 1 # Partition number 1
	echo   # First sector default
	echo +$SWAP\G # Size: 4G
	echo t # change partition type
	echo 82 # to swap
	echo n # New partition
	echo p # Primary
	echo 2 # Number 2
	echo   # First sector default
	echo   # Size: the rest of the disk
	echo t # change partition type
	echo 2 # choose partition number 2
	echo 83 # to Linux (to make sure it is Linux)
	echo a # toggle bootable
	echo 2 # choose partition number 2
	echo w # write
	) | fdisk $DRIVE
	echo "Done"
}

diskpart_setting(){
	mkfs.ext4 -L ROOT /dev/sda2
	mkswap -L SWAP /dev/sda1

	swapon /dev/disk/by-label/SWAP
	mount /dev/disk/by-label/ROOT /mnt
	mkdir /mnt/boot
	mkdir /mnt/home
}

check_internet(){
	[ "$(ping -q -c 1 -W 1 artixlinux.org)" ] && echo " [ OK ] Connected to Internet" || exit 1
}

init_install(){
	check_internet && pacman -Syy
	basestrap /mnt base base-devel openrc linux linux-firmware
	echo "Installation will start in 5 second...." && sleep 5s && echo "Installing..."
	fstabgen -U /mnt >>/mnt/etc/fstab
	echo -e "\nArtix Linux has been install, configuring..."
	artools-chroot /mnt
}

user_zone(){
	echo -e "\nRegion: (Default: Asia)"
	read -r REGION
	[ -z $REGION ] && REGION="Asia"
	echo -e "\nNearest Big City: (Default: Jakarta)"
	read -r CITY
	[ -z $CITY ] && CITY="Jakarta"
	cat /usr/share/zoneinfo/$REGION/$CITY >/dev/null 2>/dev/null || echo "Zone is not found, please try again" && user_zone
}

local_setting(){
	#clock
	user_zone
	ln -sf /usr/share/zoneinfo/$REGION/$CITY /etc/localtime
	hwclock --systohc
	
	#locale
	sed -i 's/\#en_US\./en_US\./g' /etc/locale.gen
	locale-gen
	pacman -S grub os-prober
	grub-install --recheck /dev/sda
	grub-mkconfig -o /boot/grub/grub.cfg
}

ask_pass(){	
	echo -e "Password:"
	read -s PASS
	echo -e "\nRetype Password:"
	read -s RE_PASS
	
	[ ! "$PASS" = "$RE_PASS" ] && ask_pass
}

set_user(){
	echo -e "\nUsername:"
	read -r USER
	ask_pass
	(
	echo $PASS
	echo $PASS
	) | passwd
	
	useradd -m $USER
	(
	echo $PASS
	echo $PASS
	) | passwd $USER
	
	echo $USER > /etc/hostname
	pacman -S dhcpcd connman-openrc connman-gtk cmst
	rc-update add connmand
	ip -s link
	echo -e "\nPut in the correct interface:"
	read -r INT
	echo "
	# my Config
	config_$INT=\"dhcp\"" >> /etc/conf.d/net
	ln -s /etc/init.d/net.lo /etc/init.d/net.$INT
	rc-update add net.$INT default
	echo "
	Now type:
	exit
	umount -R /mnt	
	reboot"
	exit
}

# Installation steps
checksudo
clear
diskpart
diskpart_setting
init_install
local_setting
set_user
